### ISSUE TITLE
DiskCreator 角色问题

### ISSUE THREAD

**Issue by xiangyuanyuan** [eayun/Documents#50]
文档上介绍：DiskCreator 角色允许在用户门户对虚拟磁盘进行管理。该角色可以被应用到特定的虚拟机、数据中心、存储域、或者整个虚拟化环境之中。这使得不同的用户能够管理不同层次的虚拟资源。
虚拟磁盘创建者角色能够进行以下操作：
在指定的虚拟机或者其它资源范围内创建、编辑和删除磁盘。为虚拟磁盘修改用户权限。
DiskCreator	在分配的集群或者数据中心中能够创建、编辑、管理以及删除虚拟机磁盘。	该角色并不应用于单独的虚拟磁盘；您应该在配置为整个环境将其应用于一个用户之上。另外，您还可以为特定的数据中心、集群或者存储域应用该角色。

实际测试结果：无论给数据中心或者单独虚拟机分配该权限都不能创建/删除磁盘。

**Comment by walteryang47** [comment]
This issue was moved to eayun/ovirt-engine#17
