### ISSUE TITLE
虚拟机资源分配设置设置解释中的问题

### ISSUE THREAD

**Issue by xiangyuanyuan** [eayun/Documents#68]
其中“CPU pinning 拓扑结构”的解释：为了能绑定 vCPU 和 pCPU，迁移设置必须选择不允许迁移，并且勾选使用主机 CPU 勾选框。
实际测试结果：即使迁移设置必须选择不允许迁移，并且勾选使用主机 CPU 勾选框，仍不能设置，如果在主机设置时设置“开始运行在” “专有的”主机上，即使不设置以上两项，也可以设置。
所以，只要设置开始运行在专有的主机该选项即可。

**Comment by walteryang47** [comment]
This issue was moved to eayun/ovirt-engine#14
